main.py
import os
from flask import Flask, render_template, redirect, url_for, flash
from flask_login import FlaskLoginClient
from flask_login import LoginManager
from flask_wtf.csrf import CSRFProtect
from flask_session import Session
from flask_migrate import Migrate
from dotenv import load_dotenv

import datetime


load_dotenv('.env')

from os import environ
from routes import route, db, UserData, bcrypt

app = Flask(__name__, template_folder=os.path.abspath('templates'), static_folder=os.path.abspath('static'))

app.config["SECRET_KEY"] = environ.get('SECRET_KEY')
app.config['SQLALCHEMY_DATABASE_URI'] = "sqlite:///userdata.db"
app.config['PERMANENT_SESSION_LIFETIME'] = datetime.timedelta(minutes=1)
# app.config['MAIL_SERVER']
# app.config['MAIL_PORT']
# app.config['MAIL_USE_TLS']
# app.config['MAIL_DEBUG']
# app.config['MAIL_USERNAME']
# app.config['MAIL_PASSWORD']
# app.config['MAIL_DEFAULT_SENDER']
# app.config['MAIL_MAX_EMAILS']
# app.config['MAIL_SUPPRESS_SEND']
# app.config['MAIL_ASCII_ATTACHMENT']
# app.config['SESSION_TYPE'] = 'filesystem'

csrf= CSRFProtect(app)
login_manager = LoginManager() 
migrate =Migrate()
# serializer = Serializer('secret', 30)


# session = Session()

# check if directory exists
# if os.path.exists(UPLOAD_FOLDER.isalpha):
#     app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
# else:
#     os.mkdir(UPLOAD_FOLDER)

UPLOAD_FOLDER = environ.get('UPLOAD_FOLDER')
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

login_manager.init_app(app)
db.init_app(app)
bcrypt.init_app(app)
migrate.init_app(app, db, render_as_batch=True)
# session.init_app(app)

with app.app_context():
    db.create_all() 
    
login_manager.login_view = "route.login"

@login_manager.user_loader  
def load_user(user_id):
    # db.session.get(UserData)
    return UserData.query.get(user_id)


@migrate.configure
def configure_alembic(config):
    return config

# @app.route('/set/')
# def set():
#     session['key'] = 'value'
#     return 'ok'

# @app.route('/get/')
# def get():
#     return session.get('key', 'not set')

app.register_blueprint(route)


if __name__ == "__main__":
    app.run(debug=True)

routes.py
from flask import render_template, flash, redirect, request, url_for, Blueprint, session
from flask_login import login_required, logout_user, login_user, current_user
from form import SignUpForm, LoginForm, BlogDataForm, UserForm, RequestResetForm, ResetPasswordForm
from model import db, UserData, BlogData
from flask_bcrypt import Bcrypt
from sqlalchemy import exc, select
from sqlalchemy.orm import Session, Query
from werkzeug.utils import secure_filename
import random, math
import uuid
import os

bcrypt = Bcrypt()
route = Blueprint('route', __name__,template_folder=os.path.abspath('templates'))

@route.route('/home_page')
@login_required
def home():
    blogs = db.session.execute(db.select(BlogData)).scalars()
    return render_template('index.html', blogs= blogs)


@route.route('/admin')
def admin():
    
    return render_template('admin.html')

@route.route('/login', methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():        
        form_email = form.email.data
        db_user = UserData.query.filter(UserData.email==form_email).first()
        print(db_user)
        if form_email == db_user.email:
            if bcrypt.check_password_hash(db_user.password, form.password.data):
                login_user(db_user, remember=True)  
                session.permanent = True
                return redirect(url_for('route.home', username=db_user.username))
            else:
                flash("wrong passowrd!",'danger')
        else:
            flash("Email not Found", 'error')
    else:
        print(form.errors)
    return render_template("login.html", form=form)

@route.route('/signup', methods=['GET','POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for("route.home"))
    form = SignUpForm()
    if form.is_submitted():
        if form.password.data==form.repassword.data:
            print('passed from here')
            crypted_pass = bcrypt.generate_password_hash(form.password.data)
            new_user = UserData(username=form.username.data, email=form.email.data, password=crypted_pass)
            try:
                db.session.add(new_user)
                db.session.commit()
                return redirect(url_for('route.login'))
            except exc.IntegrityError:
                db.session.rollback()
        else:
            flash("Check Email or Password!!", 'error')
    return render_template("signup.html", form=form)

@route.route('/logout', methods=['GET','POST'])
@login_required
def logout():
    # session.pop(current_user)
    logout_user()
    return redirect(url_for('route.login'))

@route.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    # myblogs =  db.session.execute(db.select(BlogData).filter_by(user_data=current_user.id)).scalars()
    myblogs = BlogData.query.filter_by(writer_id=current_user.id).all()
    form = UserForm()
    id = current_user.id

    if form.is_submitted():

        profile_pic = request.files['profile_pic']
        pic_filename = secure_filename(profile_pic.filename)
        pic_name = str(uuid.uuid1()) + "_" + pic_filename

        user = UserData.query.get_or_404(id)
        saver = request.files['profile_pic']
        
        user.profile_pic = pic_name

        db.session.add(user)
        db.session.commit()
        upload_folder = os.environ.get('UPLOAD_FOLDER')
        abs_path = os.path.abspath(upload_folder)
        print(abs_path)
        saver.save(os.path.join(abs_path, pic_name))

    return render_template('account.html', data=current_user, form=form, myblogs=myblogs)

@route.route('/blog/<id>', methods=['GET'])
@login_required
def blog_page(id):
    blog = db.session.execute(db.select(BlogData).filter_by(id=id)).scalar_one()
    blogs = BlogData.query.all()
    return render_template('blog_page.html', blog=blog)

@route.route('/create_blog', methods=['GET', 'POST'])
@login_required
def create_blog():
    form = BlogDataForm()
    session = db.session
    
    if request.method == 'POST' and form.validate():
        title = form.title.data
        content = form.content.data
        category = form.category.data
        # check if there is any file

        blog_thumbnail = request.files['blog_thumbnail']
        print(blog_thumbnail.name)
        pic_filename = secure_filename(blog_thumbnail.filename)
        pic_name = str(uuid.uuid1()) + "_" + pic_filename
        saver = request.files['blog_thumbnail']
        upload_folder = os.environ.get('UPLOAD_FOLDER')
        abs_path = os.path.abspath(upload_folder)

        # Save the blog Title, Content and Thumbnail to BlogData Table In DB
        blog = BlogData(title=title, content=content, user_data=current_user, blog_thumbnail=pic_name, category=category)
        db.session.add(blog)
        db.session.commit()
        saver.save(os.path.join(abs_path, pic_name))

        return redirect(url_for('route.home'))
    
    return render_template('create_blog.html', form=form)
    
@route.route('/delete_blog/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_blog(id):
    blog_post = BlogData.query.get_or_404(id)

    try:
        db.session.delete(blog_post)
        db.session.commit()

        flash('Blog Post Deleted Successfully!', 'success')

        return redirect(url_for('route.account'))
    except:
        flash("Whoops! there was a problem")
        return redirect(url_for('route.account'))


@route.route('/delete_account/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_account(id):
    pass


# @route.route("/reset_password", methods=['GET', 'POST'])
# def reset_request():
#     if current_user.is_authenticated:
#         return redirect(url_for('route.home'))
#     form = RequestResetForm()
#     return render_template('reset_request.html', title='Reset Password', form=form)

@route.route('/category/<string:category>')
def filter_by_category(category):
    if category=='All':
        return redirect(url_for('route.home'))
    else:
        # category = db.session.execute(db.select(BlogData).filter_by(category=category)).scalars()
        category = BlogData().query.filter_by(category=category).all()
        
        
        # return redirect(url_for('route.home', blogs= category))
    
    return render_template('index.html', blogs= category)

templates/account.html
{% extends 'master.html' %}

{% block content %}
<style>
    @import url('https://fonts.googleapis.com/css?family=Lato:300,400,700,900');

/* button{
	background-color: #176655;
	color: white;
	height: 30px;
	border-radius: 4px;
	outline: none;
	border: 0px solid white;
	width: 61%;
	margin: 0px 2%;
	letter-spacing: 5px;
	padding: 5px 0px;
	text-transform: uppercase;
	box-shadow: 1px 1px 2px 2px rgba(17,66,55,0.4),
             -1px -1px 2px 2px rgba(17,66,55,0.4);
}
button:hover{
	background-color: white;
	color: #176655;
	box-shadow: 1px 1px 2px 2px rgba(17,66,55,0.4),
             -1px -1px 2px 2px rgba(17,66,55,0.4);
}

input[type="text"],input[type="email"]{
	background-color: transparent;
	box-shadow: 1px 1px 2px 2px rgba(17,66,55,0.4),
             -1px -1px 2px 2px rgba(17,66,55,0.4);

	width: 100%;
	line-height: 2.0;
	border: 0px solid white;
	color: #176655;
	font-size: 15px;
}
 */



/* #admin_information *{
	margin:2%;
}
*/
/* table{
	border: none;
	background-color: #176655;
	width: 100%;
	padding: 10px 40px;
	font-family: 'Lato';
	text-transform: uppercase;
	letter-spacing: 2px;
	border-bottom: 0.5px solid gray;

} */
/* tr{
	padding: 0 auto;
	margin: 0 auto;
    
}
td{
	color: white;
	background-color: #176655;
	padding: 5px 5px;
	text-align: center;
	border-radius: 4px;
}  */

body{
    background:#eee;
    overflow: scroll;
    align-items: center;
}

.card{
    border:none;
    position:relative;
    overflow:hidden;
    border-radius:8px;
    cursor:pointer; 
}

.card:before{
    content:"";
    position:absolute;
    left:0;
    top:0;
    width:4px;
    height:100%;
    background-color:#E1BEE7;
    transform:scaleY(1);
    transition:all 0.5s;
    transform-origin: bottom
}

.card:after{
    
    content:"";
    position:absolute;
    left:0;
    top:0;
    width:4px;
    height:100%;
    background-color:#8E24AA;
    transform:scaleY(0);
    transition:all 0.5s;
    transform-origin: bottom
}

.card:hover::after{
    transform:scaleY(1);
}

.fonts{
    font-size:11px;
}

.social-list{
    display:flex;
    list-style:none;
    justify-content:center;
    padding:0;
}

.social-list li{
    padding:10px;
    color:#8E24AA;
    font-size:19px;
}


.buttons button:nth-child(1){
       border:1px solid #8E24AA !important;
       color:#8E24AA;
       height:40px;
}

.buttons button:nth-child(1):hover{
       border:1px solid #8E24AA !important;
       color:#fff;
       height:40px;
       background-color:#8E24AA;
}

.buttons button:nth-child(2){
       border:1px solid #8E24AA !important;
       background-color:#8E24AA;
       color:#fff;
        height:40px;
}
.profile-update{
    width: 950px;
}

.select {
  position: relative;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  box-shadow: var(--shadow);
  border-radius: 10px;
  margin-top: 0.3rem;
  background: white;
  margin-top: 5vh;
  padding: 20px;
}

.select:hover{
    background-color: #8E24AA;
    color: #fff;
}
.caret{
    width: 0;
    height: 0;
    border-left: 5px solid transparent;
    border-right: 5px solid transparent;
    border-top: 6px solid #fff; 
    transition: 0.3s;
    margin-top: 10px;
}
.caret-rotate{
    transform: rotate(180deg);
}



.update-form{
    padding: 0.6em 0.8em;
    background-color: #fff;
    margin-top: 2vh;
    border-radius: 10px;
    display: none;
}
#myblogs{
    display: flex;
    flex-direction: column;
    background-color: #fff;
    padding: 20px;
    
}

</style>

<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-7">
            <div class="card p-3 py-4">
                <div class="text-center">
                    <img src="{{url_for('static', filename='images/{}'.format(data.profile_pic))}}" width="100" height="100" class="rounded-circle">
                </div>
                
                <div class="text-center mt-3">
                    <span class="bg-secondary p-1 px-4 rounded text-white">Pro</span>
                    <h5 class="mt-2 mb-0">{{ data.username }}</h5>
                    
                    <span>UI/UX Designer</span>
                    
                    <div class="px-4 mt-1">
                        <p class="fonts">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
                    
                    </div>
                    
                    <ul class="social-list">
                        <li><i class="fa fa-facebook"></i></li>
                        <li><i class="fa fa-dribbble"></i></li>
                        <li><i class="fa fa-instagram"></i></li>
                        <li><i class="fa fa-linkedin"></i></li>
                        <li><i class="fa fa-google"></i></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    
</div>

<div class="container profile-update">
    <div class="select">
        <span >Update Profile</span>
        <div class="caret"></div>
    </div>

    <div class="update-form">
        <form action="" method="post" enctype="multipart/form-data" > 
            <!-- <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/> -->

            {{ form.csrf_token }}

            {{ form.username.label(class='form-label mt-2') }}
            {{ form.username(class='form-control')}}

            {{ form.bio.label(class='form-label mt-2') }}
            {{ form.bio(class='form-control')}}

            {{ form.profile_pic.label(class='form-label mt-2') }}
            {{ form.profile_pic(class='form-control')}}

            <button class="btn btn-primary mt-2" type="submit">Submit</button>
        </form>
    </div>

</div>



{% if myblogs %}
<section class="container mt-5 col-sm-6" id="myblogs">
    <h4>My Blogs</h4>
    <table>
        <tr>
            <th>Blog</th>
            <th class="ml-5">Delete</th>
        </tr>
        {% for blogs in myblogs %}
            <tr>
                <td>{{ blogs.title }}</th>
                <td><a href="{{ url_for('route.delete_blog', id=blogs.id) }}" class="btn btn-danger">Delete</a></th>
            </tr>
        {% endfor %}
        
    </table>

    <!-- {{ myblogs }} -->
</section>
{% endif %}


<script>
    let dropMenu = document.querySelector('.drop-menu')
    let select = document.querySelector('.select')
    let form = document.querySelector('.update-form')
    let caret = document.querySelector('.caret')

    select.addEventListener('click', ()=>{
        form.style.display = ((form.style.display!='none') ? 'none' : 'block');
        caret.classList.toggle('caret-rotate')
    })
    
</script>

{% endblock %}

templates/create_blog.html
{% extends 'master.html' %}

{% block content %}

<style>
    li{
        list-style-type: none;
    }
</style>

<div class="container ">
    <form action="" method="post" class="d-flex flex-column p-5" enctype="multipart/form-data">
        <!-- <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/> -->

        {{ form.csrf_token }}

        <div class="form-group">
            {{ form.title.label }}
            {{ form.title(class="col-sm-6 form-control") }}
        </div>

        <div class="form-group">
            {{ form.content.label }}
            {{ form.content(class="form-control", rows=8) }}
        </div>


        <div class="form-group">
            {{ form.category.label }}
            {{ form.category(class="form-control", rows=8) }}
        </div>

        <!-- <input class="form-control" type="image"> -->
        
        <div class="form-group">
            {{ form.blog_thumbnail.label(class='form-label') }}
            {{ form.blog_thumbnail(class="form-control", rows=8) }}
        </div>


        {{ form.create(class="btn col-sm-1 btn-primary mt-3") }}

    </form>

</div>


{% endblock content %}  

templates/index.html
{% extends 'master.html' %}

{% block content %}

    <section id="trending-blog" class="d-flex m-5">
        <div class="row">
            <div class="col-4" id="categories">
                <h3>Categories</h3>
                <ul>
                    <li class="cate"><a href="{{ url_for('route.filter_by_category', category='All' )}}">All</a></li>
                    <li class="cate"><a href="{{ url_for('route.filter_by_category' , category='Backend' )}}">Backend</a></li>
                    <li class="cate"><a href="{{ url_for('route.filter_by_category' , category='Frontend' )}}">Frontend</a></li>
                    <li class="cate"><a href="{{ url_for('route.filter_by_category' , category='Blockchain' )}}">Blockchain</a></li>
                    <li class="cate"><a href="{{ url_for('route.filter_by_category', category='Cybersecurity' )}}">Cybersecurity</a></li>
                </ul>
            </div>
            <section class="articles col-8">
                {% for blog in blogs %}
                {% if blog %}
                <article>

                    <div class="article-wrapper">
                        <figure>
                            <img src="{{url_for('static', filename='images/{}'.format(blog.blog_thumbnail))}}" alt="">
                        </figure>
                    </div>
                    <div class="article-body">
                        <a href="{{ url_for('route.blog_page', id=blog.id ) }}">
                            <h5>{{ blog['title'] }}</h5>
                            </a>
                        <p class="card-text">{{ blog.user_data.username }}</p>
                        <a href="{{ url_for('route.blog_page', id=blog.id ) }}" class="read-more">
                            Read more <span class="sr-only">about this is some title</span>
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd" />
                            </svg>
                        </a>
                    </div>
                </article>
                    
                {% else %}
                    <p>No Blogs</p>
                {% endif %}
            {% endfor %}
            </section>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script>

        let cateList = document.querySelectorAll('.cate');

        cateList.forEach(function(elem){
            elem.addEventListener('click', function() {
                $.ajax({
                    url : "url_for('route.filter_by_category')",
                    method : "GET",
                    accepts: {
                        mycustomtype: 'application/x-some-custom-type'
                    },
                    data: $(this.Text)
                });
            });
        });

    </script>

{% endblock %}

templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/navbar_style.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Anta&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <title>Nexus</title>
</head>
<body>
    


    <nav class="navbar navbar-extend-lg nabar-light navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <a href="{{ url_for('route.home') }}" class="navbar-brand mb-0 h1">Nexus</a>
            <ul class="nav-links">
<!-- <li><a href="{{ url_for('route.home') }}">Home</a></li> -->
                <!-- <li><a href="">About</a></li> -->
                <li>
                    <a href="#"><i class="bi bi-person-circle"></i>
                    </a>
                    <!-- <input type="checkbox" id="showDrop">
                    <label for="showDrop" class="mobile-item">Dropdown Menu</label> -->
                    <ul class="drop-menu">
                        {% if current_user.is_authenticated %}
                            <li><a href="{{ url_for('route.account') }}">Account</a></li>
                            <li><a href="{{ url_for('route.create_blog') }}">Create Blog</a></li>
                            <li><a href="{{ url_for('route.logout') }}">Log Out</a></li>
                            
                        {% else %}
                            <li><a href="{{ url_for('route.login') }}">Login</a></li>
                            <li><a href="{{ url_for('route.signup') }}">Signup</a></li>
                        {% endif %}
                        <!-- <li><a href="#">Create Blog</a></li> -->
                    </ul>
                </li>
            </ul>
        </div>
    </nav>

    {# with messages = get_flashed_messages() #}  
    {# if messages #}  
          {# for message in messages #}  
               <!-- <p class="alert alert-success" role="alert">{{ message }}</p>   -->
            {# endfor #}  
        {# endif #}  
    {# endwith #} 

    {# if error #}  
        <!-- <p><strong>Error</strong>: {{error}}</p>   -->
    {# endif #} 

    {% block content %}


    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/static-favicon@2.0.0-alpha/index.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
</body>
</html>